# Uncomment the next line to define a global platform for your project
platform :ios, '14.5'

target 'JSON' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for JSON
  
  	pod 'Moya/RxSwift', '~> 14.0'
	pod 'RxCocoa', '5.1.1'
	pod 'Moya', '~> 14.0'
	pod 'RxSwift', '5.1.2'


end
